name: GitHub Actions Workflow Example

on:
 push:
    branches:
      - master
 pull_request:
    branches:
      - master

jobs:
 build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install Dependencies
      run: |
        echo "Hello World"
        echo "Allah is good"

    - name: Run Linter
      run: |
       echo Allah is good 
       echo May allah protect us 

    - name: Run Tests
      run: |
        echo coding is good
        echo code with enough energy